package dishashmap.hashmap_servPackage;

/**
* dishashmap/hashmap_servPackage/AlreadyExistsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dishashmap.idl
* vendredi 4 avril 2014 12 h 40 CEST
*/

public final class AlreadyExistsHolder implements org.omg.CORBA.portable.Streamable
{
  public dishashmap.hashmap_servPackage.AlreadyExists value = null;

  public AlreadyExistsHolder ()
  {
  }

  public AlreadyExistsHolder (dishashmap.hashmap_servPackage.AlreadyExists initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = dishashmap.hashmap_servPackage.AlreadyExistsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    dishashmap.hashmap_servPackage.AlreadyExistsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return dishashmap.hashmap_servPackage.AlreadyExistsHelper.type ();
  }

}
