package dishashmap.hashmap_servPackage;


/**
* dishashmap/hashmap_servPackage/AlreadyExists.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dishashmap.idl
* vendredi 4 avril 2014 12 h 40 CEST
*/

public final class AlreadyExists extends org.omg.CORBA.UserException
{
  public String reason = null;

  public AlreadyExists ()
  {
    super(AlreadyExistsHelper.id());
  } // ctor

  public AlreadyExists (String _reason)
  {
    super(AlreadyExistsHelper.id());
    reason = _reason;
  } // ctor


  public AlreadyExists (String $reason, String _reason)
  {
    super(AlreadyExistsHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class AlreadyExists
