package calculator;

/**
* calculator/serv_calcHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculator.idl
* vendredi 28 mars 2014 12 h 03 CET
*/

public final class serv_calcHolder implements org.omg.CORBA.portable.Streamable
{
  public calculator.serv_calc value = null;

  public serv_calcHolder ()
  {
  }

  public serv_calcHolder (calculator.serv_calc initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = calculator.serv_calcHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    calculator.serv_calcHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return calculator.serv_calcHelper.type ();
  }

}
