package calculator;


/**
* calculator/serv_calcHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculator.idl
* vendredi 28 mars 2014 12 h 03 CET
*/

abstract public class serv_calcHelper
{
  private static String  _id = "IDL:calculator/serv_calc:1.0";

  public static void insert (org.omg.CORBA.Any a, calculator.serv_calc that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static calculator.serv_calc extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (calculator.serv_calcHelper.id (), "serv_calc");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static calculator.serv_calc read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_serv_calcStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, calculator.serv_calc value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static calculator.serv_calc narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof calculator.serv_calc)
      return (calculator.serv_calc)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      calculator._serv_calcStub stub = new calculator._serv_calcStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static calculator.serv_calc unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof calculator.serv_calc)
      return (calculator.serv_calc)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      calculator._serv_calcStub stub = new calculator._serv_calcStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
