package calculator;


/**
* calculator/serv_calc.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculator.idl
* vendredi 28 mars 2014 12 h 03 CET
*/

public interface serv_calc extends serv_calcOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface serv_calc
