package calculator;


/**
* calculator/serv_calcPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculator.idl
* vendredi 28 mars 2014 12 h 03 CET
*/

public abstract class serv_calcPOA extends org.omg.PortableServer.Servant
 implements calculator.serv_calcOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("add", new java.lang.Integer (0));
    _methods.put ("sub", new java.lang.Integer (1));
    _methods.put ("mult", new java.lang.Integer (2));
    _methods.put ("div", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // calculator/serv_calc/add
       {
         int val1 = in.read_long ();
         int val2 = in.read_long ();
         int $result = (int)0;
         $result = this.add (val1, val2);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // calculator/serv_calc/sub
       {
         int val1 = in.read_long ();
         int val2 = in.read_long ();
         int $result = (int)0;
         $result = this.sub (val1, val2);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 2:  // calculator/serv_calc/mult
       {
         int val1 = in.read_long ();
         int val2 = in.read_long ();
         int $result = (int)0;
         $result = this.mult (val1, val2);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 3:  // calculator/serv_calc/div
       {
         try {
           int val1 = in.read_long ();
           int val2 = in.read_long ();
           int $result = (int)0;
           $result = this.div (val1, val2);
           out = $rh.createReply();
           out.write_long ($result);
         } catch (calculator.serv_calcPackage.ZeroDiv $ex) {
           out = $rh.createExceptionReply ();
           calculator.serv_calcPackage.ZeroDivHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:calculator/serv_calc:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public serv_calc _this() 
  {
    return serv_calcHelper.narrow(
    super._this_object());
  }

  public serv_calc _this(org.omg.CORBA.ORB orb) 
  {
    return serv_calcHelper.narrow(
    super._this_object(orb));
  }


} // class serv_calcPOA
