package calculator;


/**
* calculator/serv_calcOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculator.idl
* vendredi 28 mars 2014 12 h 03 CET
*/

public interface serv_calcOperations 
{
  int add (int val1, int val2);
  int sub (int val1, int val2);
  int mult (int val1, int val2);
  int div (int val1, int val2) throws calculator.serv_calcPackage.ZeroDiv;
} // interface serv_calcOperations
