package dishashmap;


/**
* dishashmap/hashmap_servPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dishashmap.idl
* vendredi 4 avril 2014 12 h 40 CEST
*/

public class hashmap_servPOATie extends hashmap_servPOA
{

  // Constructors

  public hashmap_servPOATie ( dishashmap.hashmap_servOperations delegate ) {
      this._impl = delegate;
  }
  public hashmap_servPOATie ( dishashmap.hashmap_servOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public dishashmap.hashmap_servOperations _delegate() {
      return this._impl;
  }
  public void _delegate (dishashmap.hashmap_servOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public boolean containsKey (String key)
  {
    return _impl.containsKey(key);
  } // containsKey

  public dishashmap.Valeur get (String key)
  {
    return _impl.get(key);
  } // get

  public void set (String key, dishashmap.Valeur val) throws dishashmap.hashmap_servPackage.AlreadyExists
  {
    _impl.set(key, val);
  } // set

  private dishashmap.hashmap_servOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class hashmap_servPOATie
