package dishashmap;


/**
* dishashmap/hashmap_serv.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dishashmap.idl
* vendredi 4 avril 2014 12 h 40 CEST
*/

public interface hashmap_serv extends hashmap_servOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface hashmap_serv
