package dishashmap;


/**
* dishashmap/hashmap_servOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dishashmap.idl
* vendredi 4 avril 2014 12 h 40 CEST
*/

public interface hashmap_servOperations 
{
  boolean containsKey (String key);
  dishashmap.Valeur get (String key);
  void set (String key, dishashmap.Valeur val) throws dishashmap.hashmap_servPackage.AlreadyExists;
} // interface hashmap_servOperations
