package dishashmap;


/**
* dishashmap/hashmap_servPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dishashmap.idl
* vendredi 4 avril 2014 12 h 40 CEST
*/

public abstract class hashmap_servPOA extends org.omg.PortableServer.Servant
 implements dishashmap.hashmap_servOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("containsKey", new java.lang.Integer (0));
    _methods.put ("get", new java.lang.Integer (1));
    _methods.put ("set", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // dishashmap/hashmap_serv/containsKey
       {
         String key = in.read_string ();
         boolean $result = false;
         $result = this.containsKey (key);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // dishashmap/hashmap_serv/get
       {
         String key = in.read_string ();
         dishashmap.Valeur $result = null;
         $result = this.get (key);
         out = $rh.createReply();
         dishashmap.ValeurHelper.write (out, $result);
         break;
       }

       case 2:  // dishashmap/hashmap_serv/set
       {
         try {
           String key = in.read_string ();
           dishashmap.Valeur val = dishashmap.ValeurHelper.read (in);
           this.set (key, val);
           out = $rh.createReply();
         } catch (dishashmap.hashmap_servPackage.AlreadyExists $ex) {
           out = $rh.createExceptionReply ();
           dishashmap.hashmap_servPackage.AlreadyExistsHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:dishashmap/hashmap_serv:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public hashmap_serv _this() 
  {
    return hashmap_servHelper.narrow(
    super._this_object());
  }

  public hashmap_serv _this(org.omg.CORBA.ORB orb) 
  {
    return hashmap_servHelper.narrow(
    super._this_object(orb));
  }


} // class hashmap_servPOA
