package dishashmap;


/**
* dishashmap/ValeurPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dishashmap.idl
* vendredi 4 avril 2014 12 h 40 CEST
*/

public abstract class ValeurPOA extends org.omg.PortableServer.Servant
 implements dishashmap.ValeurOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("get", new java.lang.Integer (0));
    _methods.put ("set", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // dishashmap/Valeur/get
       {
         dishashmap.Valeur $result = null;
         $result = this.get ();
         out = $rh.createReply();
         dishashmap.ValeurHelper.write (out, $result);
         break;
       }

       case 1:  // dishashmap/Valeur/set
       {
         dishashmap.Valeur val = dishashmap.ValeurHelper.read (in);
         this.set (val);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:dishashmap/Valeur:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Valeur _this() 
  {
    return ValeurHelper.narrow(
    super._this_object());
  }

  public Valeur _this(org.omg.CORBA.ORB orb) 
  {
    return ValeurHelper.narrow(
    super._this_object(orb));
  }


} // class ValeurPOA
