package dishashmap;


/**
* dishashmap/ValeurOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dishashmap.idl
* vendredi 4 avril 2014 12 h 40 CEST
*/

public interface ValeurOperations 
{
  dishashmap.Valeur get ();
  void set (dishashmap.Valeur val);
} // interface ValeurOperations
