package calculator.serv_calcPackage;

/**
* calculator/serv_calcPackage/ZeroDivHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculator.idl
* vendredi 28 mars 2014 12 h 03 CET
*/

public final class ZeroDivHolder implements org.omg.CORBA.portable.Streamable
{
  public calculator.serv_calcPackage.ZeroDiv value = null;

  public ZeroDivHolder ()
  {
  }

  public ZeroDivHolder (calculator.serv_calcPackage.ZeroDiv initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = calculator.serv_calcPackage.ZeroDivHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    calculator.serv_calcPackage.ZeroDivHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return calculator.serv_calcPackage.ZeroDivHelper.type ();
  }

}
