package calculator.serv_calcPackage;


/**
* calculator/serv_calcPackage/ZeroDiv.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from calculator.idl
* vendredi 28 mars 2014 12 h 03 CET
*/

public final class ZeroDiv extends org.omg.CORBA.UserException
{
  public String reason = null;

  public ZeroDiv ()
  {
    super(ZeroDivHelper.id());
  } // ctor

  public ZeroDiv (String _reason)
  {
    super(ZeroDivHelper.id());
    reason = _reason;
  } // ctor


  public ZeroDiv (String $reason, String _reason)
  {
    super(ZeroDivHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class ZeroDiv
